version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run: npx cypress run allure=true --browser chrome
      - run:
          name: Generate `Allure report` html report
          when: always
          command: yarn allure:report
      - store_artifacts:
          name: Uploading cypress/videos artifacts
          path: cypress/videos
      - store_artifacts:
          name: Uploading cypress/screenshots artifacts
          path: cypress/screenshots
      - store_artifacts:
          name: Uploading cypress/snapshots artifacts
          path: cypress/snapshots
      - store_artifacts:
          name: Uploading allure-report artifacts
          path: allure-report
