version: 2.1
orbs:
  allure: ayte/allure@0.1.3
description: Orb providing support for [Allure Framework](https://github.com/allure-framework/allure2)
commands:
  install:
    description: Installs Allure Framework and registers it as /usr/local/bin/allure
    parameters:
      version:
        description: Allure version to use
        type: string
        default: 2.13.2
    steps:
      - run:
          name: Allure archive download
          command: curl -L https://repo1.maven.org/maven2/io/qameta/allure/allure-commandline/2.13.2/allure-commandline-2.13.2.zip -o /tmp/allure.zip
      - run:
          name: Archive extraction
          command: unzip /tmp/allure.zip
      - run:
          name: Allure installation
          command: sudo mv allure-2.13.2/usr/local/share/allure
      - run:
          name: Allure binary symlinking
          command: sudo ln -s /usr/local/share/allure/bin/allure /usr/local/bin/allure

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0-browsers
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Install allure-commandline
          command: npm i allure-commandline
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run:
          name: Run cypress tests
          command: yarn cy:run
      - run:
          name: Generate `Allure report` html report
          when: always
          command: allure generate allure-results --clean -o allure-report
      - store_artifacts:
          name: Uploading cypress/videos artifacts
          path: cypress/videos
      - store_artifacts:
          name: Uploading cypress/screenshots artifacts
          path: cypress/screenshots
      - store_artifacts:
          name: Uploading cypress/snapshots artifacts
          path: cypress/snapshots
      - store_artifacts:
          name: Uploading allure-report artifacts
          path: allure-report
