version: 2.1
orbs:
  allure: ayte/allure@0.1.3

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0-browsers
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run:
          name: Run cypress tests
          command: yarn cy:run

      - run:
          name: install allure
          when: always
          command: allure/install

      # Version - 02
      #- install-allure:
      #    name: install allure
      #    when: always
      #    command: allure/install
      #- generate-allure:
      #    name: Generate `Allure report` html report
      #    when: always
      #    command: allure/report


      # Version - 01
      #- allure/install:
      #    name: Allure veresion
      #    when: always
      #    command: allure --version
      #- allure/report:
      #    name: Generate `Allure report` html report
      #    when: always
      #    command: allure generate allure-results --clean -o allure-report

      - store_artifacts:
          name: Uploading cypress/videos artifacts
          path: cypress/videos
      - store_artifacts:
          name: Uploading cypress/screenshots artifacts
          path: cypress/screenshots
      - store_artifacts:
          name: Uploading cypress/snapshots artifacts
          path: cypress/snapshots
      - store_artifacts:
          name: Uploading allure-report artifacts
          path: allure-report
