# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: '2.1'
orbs:
  allure: ayte/allure@0.1.3
description: Orb providing support for [Allure Framework](https://github.com/allure-framework/allure2)
commands:
  install:
    description: Installs Allure Framework and registers it as /usr/local/bin/allure
    parameters:
      version:
        description: Allure version to use
        type: string
        default: 2.13.1
    steps:
      - run:
          name: Allure archive download
          command: curl -L https://github.com/allure-framework/allure2/releases/download/2.13.2/allure-commandline-2.13.2.zip -o /tmp/allure.zip
      - run:
          name: Archive extraction
          command: unzip /tmp/allure.zip
      - run:
          name: Allure installation
          command: sudo mv allure-2.13.2/usr/local/share/allure
      - run:
          name: Allure binary symlinking
          command: sudo ln -s /usr/local/share/allure/bin/allure /usr/local/bin/allure
  report:
    description: Generates report using Allure Framework
    parameters:
      configuration-path:
        description: Path to Allure configuration, uses default one if omitted
        type: string
        default: /usr/local/share/allure/config/allure.yml
      target-path:
        description: Path for report directory
        type: string
        default: allure-report
      results-path:
        description: Path to directory with test results
        type: string
        default: allure-results
      artifact-path:
        description: Path that will be used when storing result as artifact
        type: string
        default: Report/Allure
    steps:
      - run:
          name: Allure report generation
          command: |
            allure generate
      #- store_artifacts:
      #    path: << parameters.target-path >>
      #    destination: << parameters.artifact-path >>
